webapplication/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Student(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    first_name = db.Column(db.String(80))
    last_name = db.Column(db.String(80))
    mobile_num = db.Column(db.Integer(), unique=True, nullable=False)
    email_id = db.Column(db.String(50), unique=True, nullable=False)
    gender = db.Column(db.String(10), unique=True, nullable=False)
    d_o_b = db.Column(db.String(15))
    qualification = db.Column(db.String(50))
    techStacks = db.Column(db.String(80))
    img = db.Column(db.Text, unique=True, nullable=False)
    desc = db.Column(db.String(500))

webapplication/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path


db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'mysecretkey'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, urlprefix='/')
    app.register_blueprint(auth, urlprefix='/') 

    from .models import Student

    create_database(app)

    return app

def create_database(app):    
    if not path.exists('webapplication/' + DB_NAME):
        db.create_all(app=app)
        print('Database created!')

webapplication/auth.py
from flask import Blueprint, render_template, request, session, redirect
from flask_login import logout_user
from flask.helpers import url_for
from flask_login.utils import login_required

auth = Blueprint('auth', __name__)


class Admin:
    def __init__(self, username, password):
        self.username = username
        self.password = password


admin = []
admin.append(Admin(username="Reeves", password="studentskill"))



@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        session.pop('name', None)
        username = request.form['Uname']
        password = request.form['Pword']

        admin_login = [x for x in admin if x.username == username][0]
        if admin_login and admin_login.password == password:  
            session['name'] = username
            return redirect(url_for('views.homepage'))
    
    return render_template("login.html")


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('/auth.login'))

webapplication/views.py
from flask import Blueprint, render_template, request, url_for
from flask_login import current_user
from werkzeug.utils import redirect
from .models import Student
from . import db

views = Blueprint('views', __name__)

@views.route('/homepage', methods=['GET', 'POST'])
def homepage():
    if request.method == 'POST':
        record = request.form.get('newRecord')
        if record == "Enter new student record":
            return redirect(url_for('views.create_record'))

    return render_template("homePage.html", name="homePage", students = Student.query.all())


@views.route('/create_record', methods=['GET', 'POST'])
def create_record(): 
    if request.method == 'POST':
        first_name = request.form.get('fname')
        last_name = request.form.get('lname')
        mobile_number = request.form.get('mobileNo')
        email = request.form.get('email')
        sex = request.form.get('sex')
        date = request.form.get('date')
        qualification = request.form.get('qualification')
        tech = request.args.get('tech')
        image = request.form.get('img')
        description = request.form.get('desc')

        new_student = Student(first_name=str(first_name), last_name=str(last_name),  mobile_num=int(mobile_number), email_id=str(email),
        gender=str(sex), d_o_b=date, qualification=str(qualification), techStacks=str(tech), img=image, desc=str(description))
        print(tech)
        print(first_name)
        print(sex)
        db.session.add(new_student)
        db.session.commit()
        return redirect(url_for('views.homepage'))

    return render_template('student_creation_tab.html', name='creation_tab')


@views.route('/update_record/<int:id>', methods=['GET', 'POST'])
def update_record(id):
    record_to_update = Student.query.get_or_404(id)
    
    if request.method == 'POST':
        if record_to_update:
            db.session.delete(record_to_update)
            db.session.commit()

        first_name = request.form.get('fname')
        last_name = request.form.get('lname')
        mobile_number = request.form.get('mobileNo')
        email = request.form.get('email')
        sex = request.form.get('sex')
        date = request.form.get('date')
        qualification = request.form.get('qualification')
        tech = request.args.get('tech')
        image = request.form.get('img')
        description = request.form.get('desc')

        record_to_update = Student(first_name=str(first_name), last_name=str(last_name),  mobile_num=int(mobile_number), email_id=str(email),
        gender=str(sex), d_o_b=date, qualification=str(qualification), techStacks=str(tech), img=image, desc=str(description))
        db.session.add(record_to_update)
        db.session.commit()
        return redirect(url_for('views.create_record'))

    return render_template('student_creation_tab.html', name='update_tab')


@views.route('/delete_record/<int:id>', methods=['GET', 'POST'])
def delete_record(id):
    record_to_delete = Student.query.get_or_404(id)
    if record_to_delete:
        db.session.delete(record_to_delete)
        db.session.commit()
        return redirect(url_for('views.homepage'))

    return render_template('homePage.html', name='delete_record')            

webapplication/templates/homePage.html
<!DOCTYPE html>
<html>
  
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.0/css/bootstrap.min.css" 
  integrity="sha256-/ykJw/wDxMa0AQhHDYfuMEwVb4JHMx9h4jD4XvHqVzU=" crossorigin="anonymous" />
<!-- href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<!-- {% with msg = get_flashed_messages(with_categories=success)%}

{% if msg %}
    {% for message in msg  %} 
      {% if category =='success' %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ msg }}
            <button type="button" class="close" data-dismiss=>
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
      {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ msg }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
      {% endif %}  
    {% endfor %}

{% endif %}
{% endwith %} -->

<style>

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td,th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

.align-right {
  float: right;
  border: 0;
  margin: 20px;
}

.align-left {
  float: center;
}

.float-container {
  padding: 20px;
}

.input-group {
  width: 30%;
  float: left;
  padding: 20px;
}

.records {
  padding: 20px;
}

.child-records {
  width: 50%;
  float: left;
  padding: 20px;
}

.searchBtn {
  background-color: #4c98af;
  border: none;
  color: white;
  text-decoration: none;
  cursor: pointer;
  height: 30px;
  width: px;
}

input {
  margin-left: 10px;
  margin-bottom: 30px;
  border-radius: 10px;
  height: 45px;
  width: 200px
}

.new-records {
  float: right;
  margin-right: 20px;
  padding: 20px;
}

</style>

<body background="static/winter.jpg">

  <div class="search-container">

    <form class="navbar-form" role="search">
      <div class="input-group">
        <input class="form-control" placeholder="Name" name="srch-term" id="srch-term" type="text">
      </div>
      <div class="input-group">
        <input class="form-control" placeholder="MobileNo" name="srch-term2" id="srch-term2" type="text">
      </div>
      <div class="input-group-btn">
          <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
      </div>
      <div class="search-align-right">
        <button type="submit" class="searchBtn"><span>Search</span></button>
      </div>  
    </form>

  </div>


  <div class="records">
    <div class="child-records">
      <h2>Students Records</h2>
    </div>
  </div>

<table>
    <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Mobile No</th>
        <th>Skills</th>
    </tr>

  <tr>
    {% for student in students %}
    <td>{{ student.first_name }}</td>
    <td>{{ student.last_name }}</td>
    <td>{{ student.mobile_num }}</td>
    <td> {{ student.techStacks }} &ensp; <a href="{{ url_for('views.delete_record', id=student.id) }}"
      onclick="return confirm('Do you want to permanently delete students {{ id }}?');" title="Delete Record">
      <i class="material-icons" style="font-size:15px">delete</i></a> &ensp;  <a href="{{ url_for('views.update_record', id=student.id) }}"
      onclick="return confirm('Are you sure you want to edit {{ id }}?');" title="Update Record"> <i class="material-icons" style="font-size:15px">edit</i></a></td>
  </tr>
  {% endfor %}
</table>

<div class="new-records">
  <a href="{{ url_for('views.create_record') }}"><button>Enter new student record</button></a>
</div>

</body>
</html>

webapplication/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="static/css/login.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body background="static/winter.jpg">
<div class="div-class">
  <form action="{{ url_for('auth.login') }}" class="container" method="POST">
    <h1>Admin Login</h1>

    <label for="username"><b>Username</b></label><br>
    <input type="text" placeholder="Username" name="Uname" required><br><br>

    <label for="psw"><b>Password</b></label><br>
    <input type="password" placeholder="Enter Password" name="Pword" required><br><br>

    <a href="forgetPasswordController" target="_blank">Forget password?</a>


    <button type="submit" class="btn"><span>Login</span></button>

  </form>
</div>
</body>
</html>

webapplication/templates/student_creation_tab.html
<!DOCTYPE html>
<html>
  
<head>
  <link rel="stylesheet" href="static/css/creation_tab.css">
</head>
  
<body background="static/winter.jpg">

  <div class="div-class2">
    {% block content %}
    <form action="{{ url_for('views.create_record') }}" class="studentSkillContainer" method="POST">
      <h2>Enter a new student record</h2>
      
      <div class="name_form">
        <label for="Firstname"><b>Firstname</b></label><br>
        <input type="text" id="Firstname" placeholder="Firstname" name="fname" required><br><br>
  
        <label for="Lastname"><b>Lastname</b></label><br>
        <input type="text" id="Lastname" placeholder="Lastname" name="lname" required><br><br>
    
        <label for="MobileNo"><b>Mobile No</b></label><br>
        <input type="number" id="MobileNo" placeholder="Mobile No" name="mobileNo" required><br><br>

        <label for="Email"><b>Email ID</b></label><br>
        <input type="text" id="Email" placeholder="Email" name="email" multiple required><br><br>
      </div>

      <p>Please select your gender:</p>
      <div class="gender">
        <label for="male">Male</label>
        <input type="radio" name="sex" id="male" value="Male">
        <label for="female">Female</label>
        <input type="radio" name="sex" id="female" value="Female">
      </div> 

      <p>Please select your date of birth:</p>
      <input type="date" id="start" name="date"
       min="1970-01-01" max="2002-12-31"><br><br>

      <label for="qualification">Select your Qualification:</label>
      <select name="qualification" id="qual">
        <option value="b-tech">B-Tech</option>
        <option value="mca">MCA</option>
        <option value="grad">Graduation</option>
        <option value="post-grad">Post-Graduation</option>
        <option value="mba">MBA</option>
        <option value="others">Others-Graduation</option>
      </select> 

      <p>Check all relevant skills:</p>

      
      <div class="gender">
        <label for="languagetech">Java, Python or .Net</label>
        <input type="checkbox" name="skills" id="languagetech" value="Java, Python or .Net">
        <label for="database">Database</label>
        <input type="checkbox" name="skills" id="database" value="Database">
      </div> 
    

      <label for="img">Upload image:</label>
      <input type="file" id="img" name="img" accept="image/*"><br><br>
      
      <div class="desc">
        <label for="description">Description (up to 500 characters):</label><br>
        <textarea id="description" required rows="6" cols="50" name="desc"  placeholder="Brief description of student"></textarea><br><br>
      </div>

      <button type="submit" class="saveBtn"><span>Save Record</span></button>
    
    </form>
    {% endblock %}
  </div>